#!/bin/sh
set -xe

URL=https://github.com/aragilar/system_bootstrap
REPO=~/system_bootstrap
USER_MAKEFILE=Makefile.user

if [ ! -e "$REPO" ]; then
    git clone "$URL" "$REPO"
else
    pushd "$REPO"
    git fetch --all
    git merge --ff-only
    popd
fi

# do actual install/setup
make -C "$REPO" -f "$USER_MAKEFILE" initial-setup

if [ ! -e Makefile ]; then
    ln -s "$REPO"/"$USER_MAKEFILE" Makefile
fi
