#!/bin/sh

set -xe

URL=https://github.com/aragilar/system_bootstrap
REPO=system_bootstrap
MAKEFILE=Makefile.server
INSTALL='sudo apt install -y'


# Check for git
if [ -z `which git` ]; then
    echo "Git not installed, trying sudo apt install"
    $INSTALL git
fi

# Check for make
if [ -z `which make` ]; then
    echo "make not installed, trying sudo apt install"
    $INSTALL make
fi

# get this repo
if [ ! -e "$REPO" ]; then
    git clone "$URL" "$REPO"
fi

# do actual install/setup
make -C "$REPO" -f "$MAKEFILE" setup

if [ ! -e Makefile ]; then
    ln -s "$REPO"/"$MAKEFILE" Makefile
fi
