#!/bin/sh

set -xe

URL=https://github.com/aragilar/system_bootstrap
REPO=system_bootstrap
MAKEFILE=Makefile.server
INSTALL='sudo apt install -y'


$INSTALL git make lxc

# get this repo
if [ ! -e "$REPO" ]; then
    git clone "$URL" "$REPO"
else
    pushd "$REPO"
    git fetch --all
    git merge --ff-only
    popd
fi

# do actual install/setup
make -C "$REPO" -f "$MAKEFILE" setup

if [ ! -e Makefile ]; then
    ln -s "$REPO"/"$MAKEFILE" Makefile
fi
